[versions]
# Base dependencies
minecraft = "1.21.11"
fabric-loader = "0.18.4"
fabric-loom = "1.15-SNAPSHOT"
fabric-api = "0.116.8+1.21.11"

# Additional Dependencies
resourceful-lib = "3.0.12"
resourceful-config = "3.0.8"
resourceful-cosmetics = "1.0.3"
geckolib = "4.7"
bytecodecs = "1.1.2"


[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
resourceful-lib = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21", version.ref = "resourceful-lib" }
resourceful-config = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.21", version.ref = "resourceful-config" }
resourceful-cosmetics = { module = "com.teamresourceful:resourceful-cosmetics-4j", version.ref = "resourceful-cosmetics" }
geckolib = { module = "software.bernie.geckolib:geckolib-fabric-1.21.1", version.ref = "geckolib" }
bytecodecs = { module = "com.teamresourceful:bytecodecs", version.ref = "bytecodecs"}

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }

