[versions]
# Base dependencies
minecraft = "1.21.1"
fabric-loader = "0.18.4"
fabric-loom = "1.15-SNAPSHOT"
fabric-api = "0.116.8+1.21.1"

# Additional Dependencies
recourceful-lib = "3.0.12"
resourceful-config = "3.0.8"
resourceful-cosmetics = "1.0.3"
geckolib = "4.7"


[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }


[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }

